routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/' , 'HomeController@index')->name('mainHomePage');

// Route::prefix('admin')->group(function () {
// 	Route::get('login' , 'admin\AdminController@login')->name('admin.login');
// 	Route::resource('/','admin\AdminController');
// 	Route::resource('subjects','admin\SubjectsController');
// });
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function()
{
 	Route::get('login' , 'admin\AdminController@login')->name('admin.login');
	Route::resource('/','admin\AdminController');
	Route::resource('subjects','admin\SubjectsController');
	Route::resource('sets','admin\SetsController');
	Route::resource('questions','admin\QuestionsController');
});
Route::resource('subjects','SubjectsController');
Route::resource('sets','SetsController');
Route::resource('results','ResultsController');
Route::resource('users','UsersController');


Route::get('results/print/{id}' , 'ResultsController@print')->name('result.print');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Set.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Set extends Model
{
    protected $fillable = [
        'number'	,'type',	'noofquestions'	,'subject_id',	'total_mark',	'pass_mark' , 'time'
    ];
    public function subject(){
        return $this->belongsTo('App\Subject');
    }
    public function questions(){
        return $this->hasMany('App\Question');
    }
}

app/Http/Controllers/SetsController.php
<?php

namespace App\Http\Controllers;

use App\Set;
use App\Questiontype;
use App\Subject;
use App\Question;
use Illuminate\Support\Facades\Auth;

use Illuminate\Http\Request;

class SetsController extends Controller
{
    public function show(Set $set)
    {
    	if(Auth::check())
    	{
	        $questions = Set::find($set->id)->questions;
	        $question_types = Questiontype::all();
	        $totalQuestions = Question::where('set_id' , $set->id)->whereIn('questiontype_id' , [4, 3, 5])->get();
	        $subject = Subject::where('id' , '=' , $set->subject_id)->first();
	        return view('frontend.sets.show' , ['set'=> $set , 'questions'=>$questions , 'subject'=>$subject , 'question_types'=>$question_types, 'totalQuestions'=> count($totalQuestions) ]);
	    }
	    return redirect()->route("login");
    }
}

app/Http/Controllers/admin/SetsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Set;
use App\Subject;
use App\Questiontype;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SetsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Set::all();
        return view('admin.questions.index' , ['questions'=>$questions]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->except('_token'));
        try{
            Set::create($request->except('_token'));
        }
        catch(\Exception $e){
            // dd($e);
            return back()->withInput()->with('error' , 'Subjects could not be added');
        }
        return back()->with('success' , 'Subjects adding successful.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Set  $set
     * @return \Illuminate\Http\Response
     */
    public function show(Set $set)
    {
        $questions = Set::find($set->id)->questions;
        $question_types = Questiontype::all();
        // dd($question_types);
        $subject = Subject::where('id' , '=' , $set->subject_id)->first()->name;
        return view('admin.sets.show' , ['set'=> $set , 'questions'=>$questions , 'subject'=>$subject , 'question_types'=>$question_types ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Set  $set
     * @return \Illuminate\Http\Response
     */
    public function edit(Set $set)
    {
        // $subject_id = Set::find($set->id)->subject_id;
        return view('admin.sets.edit' ,['set'=> $set  ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Set  $set
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Set $set)
    {
        $set = Set::where('id' , $set->id);
        $setUpdate = $set->update($request->except(['_token' , '_method']) );
        if($setUpdate){
            return redirect()->route('admin.subjects.show', $set->first()->subject_id)->with('success', 'set updated successfully');
        }
        //redirect
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Set  $set
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id)
    {
        //
        $findSubject = Set::find( $id);
        if($findSubject->delete()){
            return redirect()->back()->with('success', 'Set deleted successfully');
        }
        return back()->withInput()->with('error' , 'Set could not be deleted');
    }
}

resources/views/admin/sets/create.blade.php
create.blade.php

resources/views/admin/sets/edit.blade.php
@extends('admin.app')
@section('content')
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">Sets</h1><div style="float: right;">
                           
                        </div>
                        <h1 class="page-subhead-line">This is the list of sets, you can add, edit or delete. </h1>

                    </div>
                </div>
                {{-- /. ROW --}}
                <div class="row">
                <form method="post" action="{{route('admin.sets.update' , $set->id)}}" class="col-md-6 col-sm-6 col-xs-12">
                        {{ csrf_field() }}
                        {{ method_field('PUT')}} 
                       <div class="panel panel-danger">
                                <div class="panel-heading">
                                   Update Set
                                </div>
                                <div class="panel-body">
                            <div class="form-group">
                                <label class="control-label col-lg-4">Set Name</label>
                                <label><input value="{{old('number' ,$set->number)}}" type="text" name="number"></label>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="control-label col-lg-4">No. of Question</label>
                                <label><input  value="{{old('noofquestions' ,$set->noofquestions)}}"  type="number" name="noofquestions"></label>    
                                            </div>
                                            <hr>
                                        
                                             <div class="form-group">
                                <label class="control-label col-lg-4">Total Mark</label>
                                <label><input value="{{old('total_mark' ,$set->total_mark)}}"  type="number" name="total_mark"></label>
                                            </div>
                                        <hr>
                                     <div class="form-group">
                                <label class="control-label col-lg-4">Pass Mark</label>
                                <label><input value="{{old('pass_mark' ,$set->pass_mark)}}"  type="number" name="pass_mark"></label>
                                            </div>
                                    <hr>
                        <div class="form-group">
                            <label class="control-label col-lg-4">Time in Minute</label>
                            <label><input value="{{old('time' ,$set->time)}}"  type="number" name="time"></label>
                        </div>  
                            
                            </div>
                            
                            <hr>
                             <label><a href="#"> <button type="submit" class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Update</button></a></label>
                                </div>

                        </form>
            {{-- /. PAGE INNER --}}
        </div>
        {{-- /. PAGE WRAPPER --}}
    </div>
    {{-- /. WRAPPER --}}
</div>

@endsection

resources/views/admin/sets/index.blade.php
@extends('admin.app')
@section('content')
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">Sets</h1><div style="float: right;">
                           
                        </div>
                        <h1 class="page-subhead-line">This is the list of sets, you can add, edit or delete. </h1>

                    </div>
                </div>

                {{-- /. ROW --}}
                <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
               <div class="panel panel-info">
                        <div class="panel-heading">
                           SUBJECT LIST
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                           
                                            <th>Sets</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $i =1; ?>
                                        @foreach($sets as $set)
                                            <tr>
                                                <td>{{$i++}}</td>
                                                <td><a href="sets.php">{{$set->name}}</a></td>
                                                <td> <a href="{{route('admin.sets.edit', $set->id)}}" class="btn btn-primary"><i class="glyphicon glyphicon-edit"></i>Edit</a>
                                                 <a   
                                                    href="#"
                                                    onclick="
                                                    var result = confirm('Are you sure you wish to delete this Subject?');
                                                        if( result ){
                                                                event.preventDefault();
                                                                document.getElementById('delete-form').submit();
                                                        }
                                                            "
                                                            class="btn btn-danger">
                                                    <span class="glyphicon glyphicon-remove"></span> 
                                                    Delete
                                                </a>
                                                <form id="delete-form" action="{{ route('admin.sets.destroy',[$set->id]) }}" 
                                                  method="POST" style="display: none;">
                                                          <input type="hidden" name="_method" value="delete">
                                                          {{ csrf_field() }}
                                                </form>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                            </div>
                <form method="post" class="col-md-6 col-sm-6 col-xs-12" action="{{route('admin.sets.store')}}">
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                           Add Subject
                        </div>
                        <div class="panel-body">
                   
                            <div class="form-group">
                                <label class="control-label col-lg-4">Subject Name</label>
                                <label><input value="{{old('name')}}" type="text" name="name"></label>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-4">Description</label>
                                <label><textarea  type="text" name="description">{{ old('description') }}</textarea></label>
                            </div>

                            {{ csrf_field() }}
                             <label><a href="{{ route('admin.sets.index')}}"> <button type="submit"class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Add</button></a></label>
                        </div>
                    </div>
                </form>
            {{-- /. PAGE INNER --}}
        </div>
        {{-- /. PAGE WRAPPER --}}
    </div>
    {{-- /. WRAPPER --}}
</div>

@endsection

resources/views/admin/sets/show.blade.php
@extends('admin.app')
@section('content')
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">Set no: {{$set->number}}</h1><div style="float: right;">
                        
                        </div>
                        <h1 class="page-subhead-line">This is the list of questions, you can add, edit or delete.</h1>

                    </div>
                </div>
                <!-- /. ROW  -->
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                       <div class="panel panel-info">
                                <div class="panel-heading">
                                   Set of {{$subject}}
                                </div>
                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered table-hover">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                   
                                                    <th>Questions</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <?php $i = 1; ?>
                                            <tbody>
                                                @foreach($questions as $question)
                                                    @if($question-> questiontype_id != 1)
                                                        <tr>
                                                            <td>{{$i++}}</td>
                                                            <td>{{$question->question}}</td>
                                                            <td><a href="{{route('admin.questions.edit', $question)}}" class="btn btn-primary"><i class="glyphicon glyphicon-edit"></i>Edit</a>
                                                     <a   
                                                        href="#"
                                                        onclick="
                                                        var result = confirm('Are you sure you wish to delete this question?');
                                                            if( result ){
                                                                    event.preventDefault();
                                                                    document.getElementById('delete-form{{$question->id}}').submit();
                                                            }
                                                                "
                                                                class="btn btn-danger btn-xs">
                                                        <span class="glyphicon glyphicon-remove"></span> 
                                                        Delete
                                                    </a>
                                                    <form id="delete-form{{$question->id}}" action="{{ route('admin.questions.destroy',$question->id) }}" 
                                                      method="POST" style="display: none;">
                                                              <input type="hidden" name="_method" value="delete">
                                                              {{ csrf_field() }}
                                                    </form>
                                                    </td>
                                                        </tr>
                                                    @endif
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <form method="post" action="{{route('admin.questions.store')}}" class="col-md-6">
                        {{csrf_field()}}
                        <input type="hidden" name="set_id" value="{{$set->id}}">
                       <div class="panel panel-default">
                            <div class="panel-heading">
                               Add Questions
                            </div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label class="control-label col-lg-4">Question</label>
                                    <textarea name="question" style="width:65%;">{{old('question')}}</textarea>
                                </div>                         
                                <hr>
                                <div class="form-group">
                                    <label class="control-label col-lg-4">Type</label>
                                    <div class="btn-group">
                                        <select name="questiontype_id" data-toggle="dropdown" id='question_type_select' class="btn dropdown-toggle">Select Type <span class="caret"></span>
                                            @foreach($question_types as $question_type)
                                            <option value="{{$question_type->id}}"
                                                @if($question_type->id == old('questiontype_id') ) selected @endif 
                                                @if($question_type->id == 1 ) disabled @endif 
                                                >{{$question_type->name}}</option>
                                            @endforeach
                                        </select>
                                        
                                    </div>
                                </div>
                                <hr>
                                <div class="form-group">
                                    <label class="control-label col-lg-4">Weightage</label>
                                    <label><input type="number" name="weightage" value="{{old('weightage')}}"></label>
                                </div>
                                <hr>
                                <div class="form-group no-of-options">
                                    <label class="control-label col-lg-4">Number of options</label>
                                    <label><input id="noofoptions" type="number" name="noofoptions" value="{{old('noofoptions')}}"></label>
                                </div>
                                <hr>
                            </div>
                                <div id="mcq_question">
                                    <div class="form-group">
                                        <label class="control-label col-lg-4">Options</label>
                                       <label>
                                        <ol id="answer_options">
                                        </ol> 
                                      </label>
                                    </div>
                                    <div class="form-group">
                                    <label class="control-label col-lg-4">Correct Answer(s)</label>
                                        <label><div id = "correct_answers" >
                                            
                                        </div></label>
                                    </div>
                                </div>
                                <div id="match-the-following" >
                                    <div class="form-group" >
                                        <table class="table table-hover text-center">
                                            <thead>
                                              <tr>
                                                <th class="text-center">Left</th>
                                                <th class="text-center">Answer</th>
                                                <th class="text-center"><span>S.No.</span></th>
                                                <th class="text-center">Right</th>
                                              </tr>
                                            </thead>
                                            <tbody id="match-the-following-tbody">
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div id="question-with-subquestions" >
                                    <div class="form-group">
                                        <label class="control-label col-lg-4">No of Sub Question</label>
                                        <label><input type="number" id="numofsubq" name="numofsubq"></label>
                                    </div>
                                    <hr>
                                    <div id="sub-questions">
                                    </div>
                                </div>
                                <label class="container fluid"><a href="#"> <button type="submit" class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Add</button></a></label>
                        </div> 
                    </form>
                 </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
@endsection