routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/' , 'HomeController@index')->name('mainHomePage');

// Route::prefix('admin')->group(function () {
// 	Route::get('login' , 'admin\AdminController@login')->name('admin.login');
// 	Route::resource('/','admin\AdminController');
// 	Route::resource('subjects','admin\SubjectsController');
// });
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function()
{
 	Route::get('login' , 'admin\AdminController@login')->name('admin.login');
	Route::resource('/','admin\AdminController');
	Route::resource('subjects','admin\SubjectsController');
	Route::resource('sets','admin\SetsController');
	Route::resource('questions','admin\QuestionsController');
});
Route::resource('subjects','SubjectsController');
Route::resource('sets','SetsController');
Route::resource('results','ResultsController');
Route::resource('users','UsersController');


Route::get('results/print/{id}' , 'ResultsController@print')->name('result.print');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    protected $fillable = [
        'name',	'description'	
    ];
    public function sets(){
        return $this->hasMany('App\Set');
    }
}

app/Http/Controllers/SubjectsController.php
<?php

namespace App\Http\Controllers;

use App\Subject;
use Illuminate\Http\Request;

class SubjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        $sets = Subject::find($subject->id)->sets;
        return view('frontend.subjects.show' , ['subject'=> $subject , 'sets'=>$sets]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
        //
    }
}

app/Http/Controllers/admin/SubjectsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Subject;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SubjectsController extends  \App\Http\Controllers\Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subjects = Subject::all();
        return view('admin.subjects.index' , ['subjects'=>$subjects]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            Subject::create($request->except('_token'));
        }
        catch(\Exception $e){
            return back()->withInput()->with('error' , 'Subjects could not be added');
        }
        return back()->with('success' , 'Subjects adding successful.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        $sets = Subject::find($subject->id)->sets;
        // dd($sets);
        return view('admin.subjects.show' , ['subject'=> $subject , 'sets'=>$sets ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
        return view('admin.subjects.edit' ,['subject'=> $subject ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        $subjectUpdate = subject::where('id' , $subject->id)->update($request->except(['_token' , '_method']) );
        if($subjectUpdate){
            return redirect()->route('admin.subjects.index')->with('success', 'subject updated successfully');
        }
        //redirect
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id)
    {
        //
        $findSubject = Subject::find( $id);
        if($findSubject->delete()){
            return redirect()->route('admin.subjects.index')->with('success', 'Subject deleted successfully');
        }
        return back()->withInput()->with('error' , 'Subject could not be deleted');
    }
}

resources/views/admin/subjects/create.blade.php
create.blade.php

resources/views/admin/subjects/edit.blade.php
@extends('admin.app')
@section('content')
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">Subjects</h1><div style="float: right;">
                           
                        </div>
                        <h1 class="page-subhead-line">This is the list of subjects, you can add, edit or delete. </h1>

                    </div>
                </div>

                {{-- /. ROW --}}
                <div class="row">
                <form method="post" class="col-md-6 col-sm-6 col-xs-12" action="{{route('admin.subjects.update' , ['id'=>$subject->id])}}">
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                           Add Subject
                        </div>
                        <div class="panel-body">
                   
                            <div class="form-group">
                                <label class="control-label col-lg-4">Subject Name</label>
                                <label><input value="{{old('name' ,$subject->name )}}" type="text" name="name"></label>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-4">Description</label>
                                <label><textarea  type="text" name="description">{{ old('description' , $subject->description) }}</textarea></label>
                            </div>
                            {{ csrf_field() }}
                        	{{ method_field('PUT')}} 

                             <label><a href="{{ route('admin.subjects.index')}}"> <button type="submit"class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Submit</button></a></label>
                        </div>
                    </div>
                </form>
            {{-- /. PAGE INNER --}}
        </div>
        {{-- /. PAGE WRAPPER --}}
    </div>
    {{-- /. WRAPPER --}}
</div>

@endsection

resources/views/admin/subjects/index.blade.php
@extends('admin.app')
@section('content')
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">Subjects</h1><div style="float: right;">
                           
                        </div>
                        <h1 class="page-subhead-line">This is the list of subjects, you can add, edit or delete. </h1>

                    </div>
                </div>

                {{-- /. ROW --}}
                <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
               <div class="panel panel-info">
                        <div class="panel-heading">
                           SUBJECT LIST
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                           
                                            <th>Subjects</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $i =1; ?>
                                        @foreach($subjects as $subject)
                                            <tr>
                                                <td>{{$i++}}</td>
                                                <td><a href="{{route('admin.subjects.show', $subject->id)}}">{{$subject->name}}</a></td>
                                                <td> <a href="{{route('admin.subjects.edit', $subject->id)}}" class="btn btn-primary"><i class="glyphicon glyphicon-edit"></i>Edit</a>
                                                 <a onclick="
                                                    var result = confirm('Are you sure you wish to delete this Subject?');
                                                        if( result ){
                                                                event.preventDefault();
                                                                document.getElementById('delete-form').submit();
                                                        }
                                                            " class="btn btn-danger">
                                                    <i class="glyphicon glyphicon-remove"></i> 
                                                    Delete
                                                </a>
                                                <form id="delete-form" action="{{ route('admin.subjects.destroy',[$subject->id]) }}" 
                                                  method="POST" style="display: none;">
                                                          <input type="hidden" name="_method" value="delete">
                                                          {{ csrf_field() }}
                                                </form>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                            </div>
                <form method="post" class="col-md-6 col-sm-6 col-xs-12" action="{{route('admin.subjects.store')}}">
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                           Add Subject
                        </div>
                        <div class="panel-body">
                   
                            <div class="form-group">
                                <label class="control-label col-lg-4">Subject Name</label>
                                <label><input value="{{old('name')}}" type="text" name="name"></label>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-4">Description</label>
                                <label><textarea  type="text" name="description">{{ old('description') }}</textarea></label>
                            </div>
                            {{ csrf_field() }}
                             <label><a href="{{ route('admin.subjects.index')}}"> <button type="submit"class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Add</button></a></label>
                        </div>
                    </div>
                </form>
            {{-- /. PAGE INNER --}}
        </div>
        {{-- /. PAGE WRAPPER --}}
    </div>
    {{-- /. WRAPPER --}}
</div>

@endsection

resources/views/admin/subjects/show.blade.php
@extends('admin.app')
@section('content')
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">{{$subject->name}}</h1><div style="float: right;">
                            
                        </div>
                        <h1 class="page-subhead-line">{{$subject->description}}</h1>

                    </div>
                </div>
                <!-- /. ROW  -->
                <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
               <div class="panel panel-info">
                        <div class="panel-heading">
                           SET LIST
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                           
                                            <th>sets</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $i =1; ?>
                                        @foreach($sets as $set)
                                            <tr>
                                                <td>{{$i++}}</td>
                                                <td><a href="{{route('admin.sets.show', $set)}}">Set {{$set->number}}</a></td>
                                                <td> <a href="{{route('admin.sets.edit', $set)}}" class="btn btn-primary"><i class="glyphicon glyphicon-edit"></i>Edit</a>
                                                 <a   
                                                    href="#"
                                                    onclick="
                                                    var result = confirm('Are you sure you wish to delete this set?');
                                                        if( result ){
                                                                event.preventDefault();
                                                                document.getElementById('delete-form').submit();
                                                        }
                                                            "
                                                            class="btn btn-danger">
                                                    <span class="glyphicon glyphicon-remove"></span> 
                                                    Delete
                                                </a>
                                                <form id="delete-form" action="{{ route('admin.sets.destroy',[$set->id]) }}" 
                                                  method="POST" style="display: none;">
                                                          <input type="hidden" name="_method" value="delete">
                                                          {{ csrf_field() }}
                                                </form>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                            </div>
<form method="post" action="{{route('admin.sets.store')}}" class="col-md-6 col-sm-6 col-xs-12">
               {{csrf_field()}}
               <input type="hidden" value="{{$subject->id}}" name="subject_id">
               <div class="panel panel-danger">
                        <div class="panel-heading">
                           Add Set
                        </div>
                        <div class="panel-body">
                   
                        <div class="form-group">
                            <label class="control-label col-lg-4">Set Number</label>
                            <label><input value="{{old('number')}}"  type="number" name="number"></label>
                        </div>
                        <hr>
                        
                        <div class="form-group">
                            <label class="control-label col-lg-4">No. of Question</label>
                            <label><input value="{{old('noofquestions')}}"  type="number" name="noofquestions"></label>    
                        </div>
                                        <hr>
                                    
                        <div class="form-group">
                            <label class="control-label col-lg-4">Total Mark</label>
                            <label><input value="{{old('total_mark')}}"  type="number" name="total_mark"></label>
                        </div>
                                    <hr>
                        <div class="form-group">
                            <label class="control-label col-lg-4">Pass Mark</label>
                            <label><input value="{{old('pass_mark')}}"  type="number" name="pass_mark"></label>
                        </div>
                                    <hr>
                        <div class="form-group">
                            <label class="control-label col-lg-4">Time in Minute</label>
                            <label><input value="{{old('time')}}"  type="number" name="time"></label>
                        </div>                        
                    </div>
                    
                    <hr>
                     <label><a href="#"> <button type="submit" class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Add</button></a></label>
                </div>

                </form>

                            
        
             <!--/.ROW-->
             

            </div>
            <!-- /. PAGE INNER  -->
        </div>
    <!-- /. WRAPPER  -->
</div> 
</div>

@endsection