routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/' , 'HomeController@index')->name('mainHomePage');

// Route::prefix('admin')->group(function () {
// 	Route::get('login' , 'admin\AdminController@login')->name('admin.login');
// 	Route::resource('/','admin\AdminController');
// 	Route::resource('subjects','admin\SubjectsController');
// });
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function()
{
 	Route::get('login' , 'admin\AdminController@login')->name('admin.login');
	Route::resource('/','admin\AdminController');
	Route::resource('subjects','admin\SubjectsController');
	Route::resource('sets','admin\SetsController');
	Route::resource('questions','admin\QuestionsController');
});
Route::resource('subjects','SubjectsController');
Route::resource('sets','SetsController');
Route::resource('results','ResultsController');
Route::resource('users','UsersController');


Route::get('results/print/{id}' , 'ResultsController@print')->name('result.print');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Result.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Result extends Model
{
    protected $fillable = [
        'user_id'	,'subject_id'	,'set_id'	,'obtainedmark',	'result'
    ];
}

app/Http/Controllers/ResultsController.php
<?php

namespace App\Http\Controllers;

use App\Result;
use App\Question;
use App\Set;
use Illuminate\Http\Request;
use App\Questiontype;
use App\Subject;
use App\SelfReferenceQuestion;
use App\Rightanswer;
use App\Answer;

use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Auth;

class ResultsController extends Controller
{
    const SubQuestions = 1;
    const MCQ = 3;
    const MatchTheFollowing = 4;
    const QWSQ = 5;


    public function print(Request $request,$id  )
    {
        $currentResults = $request->session()->get('results');
        $result = Result::find($id);
        $questions = Set::find($result->set_id)->questions;
        $set = Set::find($result->set_id);
        $question_types = Questiontype::all();
        $subject = Subject::where('id' , '=' , $result->subject_id)->first();
        return view('frontend.results.print' , ['set'=> $set , 'questions'=>$questions , 'subject'=>$subject , 'question_types'=>$question_types ,'performance'=>$currentResults["results"] , 'result'=> $result, 'currentResults'=>$currentResults]);
    }
    public function checkMatchTheFollowing($question , $submittedAnswers)
    {
        $childRightAnswers = $this->getChildrenRightAnswers($question->id);
        $result = true;
        for($i = 0 ; $i < count($submittedAnswers); $i++)
        {
            if($submittedAnswers[$i] != $childRightAnswers[$i])
            {
                $result = false;
                break;
            }
        }
        return $result;
    }
    public function checkQuestionWithSubQuestions($question , $submittedAnswers)
    {
        $childRightAnswers = $this->getChildrenRightAnswers($question->id);
        $result = true;
        for($i = 0 ; $i < count($submittedAnswers); $i++)
        {
            if($submittedAnswers[$i] != $childRightAnswers[$i])
            {
                $result = false;
                break;
            }
        }
        return $result;
    }
    public function getobtainedMark($submittedAnswers, $set_id){
        $obtainedMark = 0;
        $results = [];
        $matchTheFollowing = [];             
        $printResult = [];
        $questionWithSubQuestions = [];
        // dd($submittedAnswers);
        foreach ($submittedAnswers as $questionId => $selectedAnswers) {
            $question = Question::where(['id'=>$questionId])->first();            
            if($question->questiontype_id == self::MCQ )
            {
                $rightAnswerIds = $question->rightanswers()->pluck('answer_id')->all();
                $allAnswerRight = true;

                foreach ($selectedAnswers as $key => $answerId) {
                    $results[$answerId] = false;
                    if(!in_array($answerId, $rightAnswerIds)){
                        $allAnswerRight = false;
                    }
                    else
                    {
                        $results[$answerId] = true;
                    }
                }
                if( count($selectedAnswers) < count($rightAnswerIds) ) $allAnswerRight = false;
                $printResult[$question->id] = false;
                if($allAnswerRight)
                {
                    $obtainedMark += $question->weightage;
                    $printResult[$question->id] = true;
                }
            }
            elseif ($question->questiontype_id == self::MatchTheFollowing ) 
            {
                $matchTheFollowingResult = $this->checkMatchTheFollowing($question , $selectedAnswers);
                $printResult[$question->id] = false;
                if($matchTheFollowingResult)
                {
                    $obtainedMark += $question->weightage;
                    $printResult[$question->id] = true;
                }
                $matchTheFollowing[$question->id] = [ "result" => $matchTheFollowingResult , "submittedAnswers"=>$selectedAnswers , "rightAnswers" => $this->getChildrenRightAnswers($question->id) ];
            }
            elseif ($question->questiontype_id == self::QWSQ ) 
            {
                $questionWithSubQuestionResult = $this->checkQuestionWithSubQuestions($question , $selectedAnswers);
                $printResult[$question->id] = false;
                if($questionWithSubQuestionResult)
                {
                    $obtainedMark += $question->weightage;
                    $printResult[$question->id] = true;
                }
                $questionWithSubQuestions[$question->id] = [ "result" => $questionWithSubQuestionResult , "submittedAnswers"=>$selectedAnswers , "rightAnswers" => $this->getChildrenRightAnswers($question->id) ];
            }

        }
        $questions = Set::find($set_id)->questions;
        /*make green the right answers*/
        foreach ($questions as $key => $question) {
            $rightanswers = $question->rightanswers;
            foreach ($rightanswers as $key => $answer) {
                $results[$answer->answer_id] = true;
            }
            if( $question->questiontype_id ==4 ||  $question->questiontype_id == 3)
            {
                if( !array_key_exists($question->id, $printResult)) $printResult[$question->id] = false; 
            }
        }
        // dd($results);
        return $allResults = ['obtainedmark'=>$obtainedMark , 'results'=>$results , 'matchTheFollowing'=> $matchTheFollowing , 'questionWithSubQuestions'=> $questionWithSubQuestions , 'printResult'=> $printResult];
    }
    public function store(Request $request)
    {
        $user_id = 7;
        if(Auth::check())
        {
            $user_id = Auth::user()->id;
        }
        $data = $request->except('_token');
        // dd($data);
        $submittedAnswers = $request->except(['_token' , 'subject_id','set_id', 'user_id']);
        $results = $this->getobtainedMark($submittedAnswers , $request->set_id);
        $om = $results["obtainedmark"];
        if($om>=80) $res = "Excellent";
        else if($om>=60) $res= "Good";
        else if($om>=50) $res="Okay";
        else $res= "Not good"; 
        try{
            $result = Result::create([
                "user_id"=> $user_id,
                "subject_id" => $request->subject_id,
                "set_id"=>$request->set_id,
                "obtainedmark"=>$results["obtainedmark"],
                "result"=>$res
            ]);
        }
        catch(\Exception $e){
            // dd($e);
            return back()->withInput()->with('error','failed to submit');
        }
        session(['results' => $results]);
        return redirect()->route('results.show' , $result->id );
    }

    public function show( Request $request,$id  )
    {
        $currentResults = $request->session()->get('results');
        $result = Result::find($id);
        $questions = Set::find($result->set_id)->questions;
        $set = Set::find($result->set_id);
        $question_types = Questiontype::all();
        $subject = Subject::where('id' , '=' , $result->subject_id)->first();
        return view('frontend.results.show' , ['set'=> $set , 'questions'=>$questions , 'subject'=>$subject , 'question_types'=>$question_types ,'performance'=>$currentResults["results"] , 'result'=> $result, 'currentResults'=>$currentResults]);
    }
    function getChildrenQuestions($questionId)
    {
        $childQuestions = SelfReferenceQuestion::where("parent_question_id" , "=" , $questionId )->pluck( "question_id" )->all();
        return Question::whereIn( 'id' , $childQuestions)->get();
    }
    function getChildrenRightAnswers($questionId)
    {
        $childQuestions = SelfReferenceQuestion::where("parent_question_id" , "=" , $questionId )->pluck( "question_id" )->all();
        $childRightAnswers = Rightanswer::whereIn("question_id"  , $childQuestions )->pluck( "answer_id" )->all();
        return $childRightAnswers; 
    }
}

app/Http/Controllers/admin/ResultsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Result;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ResultsController extends  \App\Http\Controllers\Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function show(Result $result)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function edit(Result $result)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Result $result)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function destroy(Result $result)
    {
        //
    }
}

resources/views/frontend/results/print.blade.php
@extends('app2')
@section('content')
<?php $img_url = asset('public/assets/images/demo/backgrounds/ahaha.jpg');?>
<div style="background-image:url({{$img_url}});">
<div class="container result" >
  <a class="btn btn-primary fl_right" onclick="myFunction()"><span class="glyphicon glyphicon-print print"></span> Print
    </a>
  <div class="resulttab"><center><h3><u>OES Quiz Marksheet</u></h3></center>

  <b>Student Name: {{auth::user()->firstname}} <span class="fl_right">Pass Mark:40</span><br> 
  <span class="fl_right">Subject: {{$subject->name}}</span>Set No.: {{$set->number}}</b>      
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="col-sm-1">#</th>
        <th class="col-sm-8">Question</th>
        <th class="col-sm-1">Result</th>
        <th class="col-sm-1">Awarded</th>
        <th class="col-sm-1">Points</th>
      </tr>
    </thead>
    <tbody>
      <?php $i = 1; ?>
      @foreach($questions as $question)
        @if($question->questiontype_id == 3 )
          <tr style="text-align: center;">
            <td style="text-align: right;">{{$i++}}</td>
            <td style="text-align: left;">{{$question->question}}</td>
            <td>
              @if($currentResults["printResult"][$question->id])
                <span class="glyphicon glyphicon-ok green"></span>
              @else
                <span class="glyphicon glyphicon-remove red"></span>
              @endif
            </td>
            <td>@if($currentResults["printResult"][$question->id]) {{$question->weightage}} @else 0 @endif</td>
            <td>{{$question->weightage}}</td>
          </tr>
        @elseif( $question->questiontype_id ==4  )
          <tr style="text-align: center;">
            <td style="text-align: right;">{{$i++}}</td>
            <td style="text-align: left;">{{$question->question}}</td>
            <td>
              @if($currentResults["printResult"][$question->id])
                <span class="glyphicon glyphicon-ok green"></span>
              @else
                <span class="glyphicon glyphicon-remove red"></span>
              @endif
            </td>
            <td>@if($currentResults["printResult"][$question->id]) {{$question->weightage}}  @else 0 @endif</td>
            <td>{{$question->weightage}}</td>
          </tr>
        @elseif( $question->questiontype_id == 5  )
          <tr style="text-align: center;">
            <td style="text-align: right;">{{$i++}}</td>
            <td style="text-align: left;">{{$question->question}}</td>
            <td>
              @if($currentResults["printResult"][$question->id])
                <span class="glyphicon glyphicon-ok green"></span>
              @else
                <span class="glyphicon glyphicon-remove red"></span>
              @endif
            </td>
            <td>@if($currentResults["printResult"][$question->id]) {{$question->weightage}}  @else 0 @endif</td>
            <td>{{$question->weightage}}</td>
          </tr>
        @endif
      @endforeach
    </tbody>
    <thead>
      <tr>
        <th class="col-sm-1">Total</th>
        <th class="col-sm-8"></th>
        <?php $om = $result->obtainedmark; $pm = $set->pass_mark; ?>
        <th class="col-sm-1" style="text-align: center;">
          @if( $om >= $pm )<span style="color: green;">Pass </span><span class="glyphicon glyphicon-ok green"></span> 
          @else Fail <span class="glyphicon glyphicon-remove red"></span> @endif
        </th>
        <th class="col-sm-1" style="text-align: center;">{{ $result->obtainedmark}}</th>
        <th class="col-sm-1" style="text-align: center;">{{ $set->total_mark }}</th>
      </tr>
    </thead>
  </table>
</div>
</div>
</div>
@endsection

<script>
function myFunction() {
    window.print();
}
</script>

resources/views/frontend/results/show.blade.php
@extends('app1')
@section('content')
  <section id="breadcrumb" class="hoc clear"> 
    
    <h6 class="heading" style="color: white;">Sets</h6>
    
    <ul style="color: white;">
      <li><a href="{{URL::to('/')}}">Home</a></li>
      <li><a href="{{route('subjects.show' , $subject->id)}}">{{$subject->name}}</a></li>
      <li><a href="{{route('sets.show' , $set->id)}}">Set {{$set->number}}</a></li>
      <li><a href="#">Results</a></li>
    </ul>
  </section>
</div>
<?php $img_url = asset('public/assets/images/demo/backgrounds/ahaha.jpg');?>
<div class="wrapper row3" style="background-image:url({{$img_url}});">
  <main class="container clear"> 

    <!-- main body -->
    <blockquote><div class="heading green">Results</div>
    <?php 
      $om = $result->obtainedmark; 
      $totalMark = $set->total_mark;
    	
      if($om >= (60*$totalMark)/100)
    	$ans_col = "green";

    	elseif($om >= (40*$totalMark)/100) 
    		$ans_col= "orange";

    	else
    		$ans_col = "red";
    ?>
    <label class="fl_right {{$ans_col}}">Score: {{$om}}</label>
    
    <div>Subject: <b><i>{{$subject->name}}</i></b></div>
    <footer>Set No: {{$set->number}}</footer>
    <a class="btn btn-primary fl_right" href="{{route('result.print' , $result->id)}}"><span class="glyphicon glyphicon-book

"></span> Marksheet
    </a>
  </blockquote> <hr>
    <form >
        <ol>
            @foreach($questions as $question)
              @if($question->questiontype_id != 1)
                <strong><li class="question">{{$question->question}}</li><div class="badge @if($currentResults['printResult'][$question->id]) weight-rightans @else weight-wrongans @endif"  >Weightage: {{$question->weightage}}</div></strong>
              @endif
              @if($question->questiontype_id == 3)
                <?php
                $i =1; 
                ?>
                    @foreach($question->answers as $answer)
                      <big><div class="checkbox disabled"><label class="
                                    @if(array_key_exists($answer->id, $performance))
                                      @if( $performance[$answer->id]== true) rightans
                                      @else wrongans
                                      @endif
                                    @endif
                       ">
                      	<input value="{{$i++}}" type="checkbox" name="{{$question->id}}" disabled><span class="label-text">{{$answer->answer}}</span>
                      </label></div></big>
                    @endforeach
                  <hr>
                @elseif($question->questiontype_id == 4)
                  @if($currentResults["matchTheFollowing"][$question->id]["result"])
                    <div class="right-match">You did it correctly.</div>
                  @else
                    <div class="wrong-match">You did it wrong.</div>
                  @endif
                @elseif($question->questiontype_id == 5)
                  @if($currentResults["questionWithSubQuestions"][$question->id]["result"])
                    <div class="right-match">You did it correctly.</div>
                  @else
                    <div class="wrong-match">You did it wrong.</div>
                  @endif
                @endif
             @endforeach
        </ol>
      {{csrf_field()}}
        <input type="hidden" value="{{$subject->id}}"  name="subject_id">
        <input type="hidden" value="{{$set->id}}"   name="set_id">
        <input type="hidden" value="1"    name="user_id">
    </form>
    </div>
    
@endsection
<style type="text/css">
	.rightans{
		color:green;
	}
	.wrongans{
		color:red;
	}
</style>